
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS customer;
CREATE TABLE customer (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (32));

DROP TABLE IF EXISTS equipment;
CREATE TABLE equipment (id INTEGER PRIMARY KEY NOT NULL UNIQUE, name VARCHAR (32) NOT NULL UNIQUE, equipObj CHAR (128));

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
